apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: http-server-hpa
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: http-server
