apiVersion: v1
kind: Service
metadata:
  labels:
    name: http-server-svc
  name: http-server-svc
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    name: http-server
  type: LoadBalancer
